### ISSUE TITLE
[Question] 1.18.2?

### ISSUE THREAD

**Issue by ConqAra** [acikek/calibrated-access#1]
Is there a 1.18.2 backport in the works or that's planned?

**Comment by acikek** [comment]
Not in the works, not planned. Do you want one? If so, why?

**Comment by ConqAra** [comment]
Big modpack thats 1.18.2 i made, i love the idea of your mod i was hoping for a 1.18.2 backport, 1.18.2 solid version of the game for me and many mods I use haven't been ported to later versions yet.

**Comment by acikek** [comment]
Knock yourself out. [Modrinth](https://modrinth.com/mod/calibrated/version/1.1.0+1.19.4), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/calibrated/files/4455364)

Note: this is probably a one-time thing. I'm in the middle of updating mods, and this was pretty quick, but I consider 1.18.2 EOL at this point and don't plan on supporting it further.
